language: android
jdk:
  - oraclejdk8
android:
  components:
    - build-tools-26.0.1
    - android-26
script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
after_success:
  - bash <(curl -s https://codecov.io/bash)